name:                esqueleto-pgcrypto
version:             0.1.0.0
github:              "githubuser/esqueleto-pgcrypto"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/esqueleto-pgcrypto#readme>

dependencies:
- base >= 4.13 && < 5
- esqueleto
- text

library:
  source-dirs: src

tests:
  esqueleto-pgcrypto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esqueleto-pgcrypto
    - QuickCheck
    - hspec
    - persistent
    - persistent-postgresql
    - monad-logger
    - transformers
    - unliftio
