name:                esqueleto-pgcrypto
version:             0.1.0.0
github:              "3kyro/esqueleto-pgcrypto"
license:             BSD3
author:              "Kyriakos Papachrysanthou"
maintainer:          "papachrysanthou.k@gmail.com"
copyright:           "2021 Kyriakos Papachrysanthou"
category:            "Database"
synopsis:            "Esqueleto support for the pgcrypto PostgreSQL module"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:  Esqueleto support for the pgcrypto PostgreSQL module        
# category:  Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/3kyro/esqueleto-pgcrypto#readme>

dependencies:
- base >= 4.13 && < 5
- esqueleto
- text

library:
  source-dirs: src

tests:
  esqueleto-pgcrypto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - esqueleto-pgcrypto
    - QuickCheck
    - hspec
    - persistent
    - persistent-postgresql
    - monad-logger
    - transformers
    - unliftio
